name: DailyQuests
version: 1.0
main: fr.norrion.daily_quests.Main
api-version: 1.13
authors: [Prototest34]

commands:
  quest:
    description: quest
    aliases: [q]
  questadmin:
    description: questadmin
    aliases: [qa]